# -*- coding: utf-8 -*-
"""FibonacciSeries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KSQsHiw6B0aUfUwEGhjmpPxpuBGJQ0b8
"""

# Python Program to print Fibonacci Series between 0 To 50

#First Number From Users
num1 = int(input("Please First Number of Fibonacci Series: "))
# Second Number in Fibonacci Series
num2= 1
#Third Number From Users
lastNum = int(input("Please Enter Last Number of Fibonacci Series: "))
#New Number Declaration
newNum=0

while newNum <= lastNum:
  print(newNum)
  newNum= num1+num2
  #Updating the Values
  num1 = num2
  num2=newNum