# -*- coding: utf-8 -*-
"""OddEvenCount.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H_D6qkk4kLmA6YpV-crXkwSLdvTE7glG
"""

userInput =  tuple(map(int, input("Enter a multiple Integer values: ").split()))
even_Count=0
odd_Count=0
for i in userInput:
  if not i%2:
    even_Count +=1
  else:
    odd_Count += 1
print("Number of Evens: ",even_Count)
print("Number of Odds: ", odd_Count)