# -*- coding: utf-8 -*-
"""ReversedString.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OThG-EZPJAbSkpwflUnb2HI6XTiALzRi
"""

#Python Code For Reverse a String
#Defining Reverse Function
def reverse(UserInput):
    str = ""
    for i in UserInput:
        str = i + str
    return str
 #Accepting User Input 
UserInput = input("Please Enter Any Word or String: ")  
print("The reversed string is : ", reverse(UserInput))